# Esempio di package generato automaticamente

automation:
  - alias: "Accendi luce al tramonto"
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: light.turn_on
        target:
          entity_id: light.soggiorno
